server:
  port: 8090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/speed?useUnicode=true&characterEncoding=utf-8&useSSL=false
    name: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariPC
      max-lifetime: 180000
      connection-timeout: 30000

---
# 热部署
spring:
  devtools:
    restart:
      enabled: true
---
# Swagger3 配置
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
